/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * API
 * Backend API for georgesheppard.dev websites
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from '../lib/custom-fetch';
export interface Recommendation {
  name: string;
  author: string;
  description: string;
  reason: string;
  amazonLink: string;
}

export interface Image {
  /** Image timestamp */
  timestamp: number;
  /** S3 object key */
  key: string;
  /** Presigned URL for downloading the image (undefined if generation failed) */
  presignedUrl?: string;
}

/**
 * Unit of measurement
 */
export type QuantityUnit = typeof QuantityUnit[keyof typeof QuantityUnit];


export const QuantityUnit = {
  none: 'none',
  mL: 'mL',
  L: 'L',
  g: 'g',
  kg: 'kg',
  cup: 'cup',
  tsp: 'tsp',
  tbsp: 'tbsp',
  quantity: 'quantity',
} as const;

export interface Quantity {
  /** Unit of measurement */
  unit: QuantityUnit;
  /** Numeric value */
  value?: number;
}

export interface Ingredient {
  /** Ingredient name */
  name: string;
  quantity: Quantity;
}

export interface Instruction {
  /** Instruction text */
  text: string;
  /** Whether this step is optional */
  optional?: boolean;
}

export interface Component {
  /** Component name */
  name: string;
  /** Component UUID */
  uuid: string;
  /** List of ingredients */
  ingredients: Ingredient[];
  /** List of instructions */
  instructions: Instruction[];
  /** Whether component can be made ahead */
  storeable?: boolean;
  /** Number of servings */
  servings?: number;
}

export interface Recipe {
  /** Recipe UUID */
  uuid: string;
  /** Recipe name */
  name: string;
  /** Recipe description */
  description: string;
  /** Recipe images */
  images: Image[];
  /** Recipe components */
  components: Component[];
}

export interface MealPlanComponent {
  /** Recipe component UUID */
  componentId: string;
  /** Number of servings */
  servings: number;
}

export interface MealPlanRecipe {
  /** Recipe UUID */
  recipeId: string;
  /** Recipe components */
  components: MealPlanComponent[];
}

export interface MealPlanDayEntry {
  /** Unix timestamp in milliseconds */
  date: number;
  /** Recipes for this day */
  plan: MealPlanRecipe[];
}

export type MealPlan = MealPlanDayEntry[];

export type GetAuthLoginParams = {
/**
 * Frontend URL to return to after login; must be in the allowed origin list
 */
redirect_uri?: string;
};

export type GetAuthCallbackParams = {
/**
 * Authorization code returned by Cognito
 */
code?: string;
/**
 * Must match the oauth_state cookie set during login
 */
state?: string;
};

export type GetAuthSession200User = {
  id: string;
  email: string;
};

export type GetAuthSession200 = {
  user: GetAuthSession200User;
};

export type GetAuthSession401 = {
  error: string;
};

export type PostAuthLogoutParams = {
redirect_uri?: string;
};

export type PostAuthLogout200 = {
  success: true;
  cognitoLogoutUrl: string;
};

export type GetApiRecommendationsId200 = {
  /** @nullable */
  recommendations: Recommendation[] | null;
  hasEmail: boolean;
  isRecurringMonthly: boolean;
  success: true;
};

export type GetApiRecommendationsId404 = {
  error: string;
  success: false;
};

export type GetApiRecommendationsId422 = {
  error: string;
  success: false;
};

export type PostApiRecommendationsAddEmailBodyRecurring = typeof PostApiRecommendationsAddEmailBodyRecurring[keyof typeof PostApiRecommendationsAddEmailBodyRecurring];


export const PostApiRecommendationsAddEmailBodyRecurring = {
  true: 'true',
  false: 'false',
} as const;

export type PostApiRecommendationsAddEmailBody = {
  id: string;
  email?: string;
  recurring?: PostApiRecommendationsAddEmailBodyRecurring;
};

export type PostApiRecommendationsAddEmail200 = {
  success: true;
} | {
  success: false;
  error: string;
};

export type PostApiRecommendationsAddEmail400 = {
  success: true;
} | {
  success: false;
  error: string;
};

export type PostApiRecommendationsAddEmail404 = {
  success: true;
} | {
  success: false;
  error: string;
};

export type PostApiRecommendationsDeleteEmailBody = {
  requestId: string;
};

export type PostApiRecommendationsDeleteEmail200 = { [key: string]: unknown };

export type PostApiRecommendationsDeleteEmail400 = {
  error: string;
};

export type PostApiRecommendationsFromBookcaseBody = {
  /** One or more bookcase images. Multiple files can be uploaded with the same field name. */
  bookcase?: Blob;
};

export type PostApiRecommendationsFromBookcase200 = {
  id: string;
  success: true;
};

export type PostApiRecommendationsFromBookcase400 = {
  error: string;
  success: false;
};

export type PostApiRecommendationsFromBookcase500 = {
  error: string;
  success: false;
};

export type GetApiQueueDueRecommendations401 = {
  error: string;
};

export type GetApiReextractRecurringBooks200 = {
  totalUsers: number;
  processedUsers: number;
  skippedUsers: number;
  failures: number;
};

export type GetApiReextractRecurringBooks401 = {
  error: string;
};

export type PostMcpAuthToken200 = {
  /** JWT token for MCP authentication */
  token: string;
  /** User ID */
  userId: string;
};

export type PostMcpAuthToken401 = {
  error: string;
};

export type GetMiseRecipes200 = {[key: string]: Recipe};

export type GetMiseRecipes401 = {
  /** Error message */
  error: string;
};

export type GetMiseRecipes500 = {
  /** Error message */
  error: string;
};

export type GetMiseRecipesSearchParams = {
/**
 * Search query string
 * @minLength 1
 */
q: string;
/**
 * Comma-separated fields to search: name,description,ingredients,instructions
 */
fields?: string;
};

export type GetMiseRecipesSearch200ResultsItem = {
  /** Recipe UUID */
  uuid: string;
  /** Recipe name */
  name: string;
  /** Recipe description */
  description: string;
  /** Flattened list of ingredient names */
  ingredients: string[];
};

export type GetMiseRecipesSearch200 = {
  /** Array of matching recipes */
  results: GetMiseRecipesSearch200ResultsItem[];
  /**
     * Number of results returned
     * @minimum 0
     */
  count: number;
};

export type GetMiseRecipesSearch400 = {
  /** Error message */
  error: string;
};

export type GetMiseRecipesSearch401 = {
  /** Error message */
  error: string;
};

export type GetMiseRecipesSearch500 = {
  /** Error message */
  error: string;
};

export type DeleteMiseRecipesUuid200 = {
  /** Whether delete was successful */
  success: boolean;
  /** UUID of deleted recipe */
  uuid: string;
};

export type DeleteMiseRecipesUuid401 = {
  /** Error message */
  error: string;
};

export type DeleteMiseRecipesUuid500 = {
  /** Error message */
  error: string;
};

export type GetMiseMealPlan401 = {
  /** Error message */
  error: string;
};

export type GetMiseMealPlan500 = {
  /** Error message */
  error: string;
};

export type PutMiseMealPlan200 = {
  /** Whether update was successful */
  success: boolean;
};

export type PutMiseMealPlan400 = {
  /** Error message */
  error: string;
};

export type PutMiseMealPlan401 = {
  /** Error message */
  error: string;
};

export type PutMiseMealPlan500 = {
  /** Error message */
  error: string;
};

export type GetMiseShoppingListParams = {
/**
 * Array of Unix timestamps (milliseconds) to include in shopping list
 */
dates?: string | string[];
};

export type GetMiseShoppingList200ItemQuantitiesItem = {
  /** Quantity value */
  value?: number;
  /** Unit of measurement */
  unit: string;
};

export type GetMiseShoppingList200Item = {
  /** Name of the ingredient */
  ingredient: string;
  /** Array of quantities with units */
  quantities: GetMiseShoppingList200ItemQuantitiesItem[];
  /** Shopping category for the ingredient */
  category: string;
  /** List of meals this ingredient belongs to */
  meals: string[];
};

export type GetMiseShoppingList401 = {
  /** Error message */
  error: string;
};

export type GetMiseShoppingList500 = {
  /** Error message */
  error: string;
};

export type PostMiseS3SignedUrlBody = {
  /** S3 object key */
  key: string;
};

export type PostMiseS3SignedUrl200 = {
  /** Signed GET URL valid for download */
  signedUrl: string;
};

export type PostMiseS3SignedUrl400 = {
  /** Error message */
  error: string;
};

export type PostMiseS3SignedUrl500 = {
  /** Error message */
  error: string;
};

export type PostMiseS3UploadBody = {
  /** Original filename */
  fileName: string;
  /** MIME type (e.g., "image/jpeg") */
  contentType: string;
};

export type PostMiseS3Upload200 = {
  /** Signed PUT URL valid for upload */
  signedUrl: string;
  /** S3 object key where file will be stored */
  key: string;
};

export type PostMiseS3Upload400 = {
  /** Error message */
  error: string;
};

export type PostMiseS3Upload401 = {
  /** Error message */
  error: string;
};

export type PostMiseS3Upload500 = {
  /** Error message */
  error: string;
};

export type PostMiseS3DeleteBody = {
  /** S3 object key to delete */
  key: string;
};

export type PostMiseS3Delete200 = {
  /** Whether delete was successful */
  success: boolean;
};

export type PostMiseS3Delete400 = {
  /** Error message */
  error: string;
};

export type PostMiseS3Delete500 = {
  /** Error message */
  error: string;
};

export type PostMiseParseRecipeBody = {
  /**
     * Natural language recipe text to parse
     * @minLength 1
     */
  recipeText: string;
  /** Recipe UUID for editing existing recipes */
  recipeId?: string;
  /** S3 key of the image to associate with this recipe (from presigned upload endpoint) */
  imageKey?: string;
};

export type PostMiseParseRecipe400 = {
  /** Error message */
  error: string;
};

export type PostMiseParseRecipe401 = {
  /** Error message */
  error: string;
};

export type PostMiseParseRecipe500 = {
  /** Error message */
  error: string;
};

export type GetTflStationsParams = {
/**
 * Station name to search for
 * @minLength 1
 */
query: string;
};

export type GetTflStations200StationsItem = {
  /** TfL StopPoint ID */
  id: string;
  /** Station name */
  name: string;
};

export type GetTflStations200 = {
  stations: GetTflStations200StationsItem[];
};

export type GetTflStations500 = {
  /** Error message */
  error: string;
};

export type GetTflArrivalsParams = {
/**
 * TfL StopPoint ID
 * @minLength 1
 */
stopPointId: string;
/**
 * Filter to a specific line, e.g. "victoria"
 */
lineId?: string;
/**
 * Filter to a specific direction
 */
direction?: GetTflArrivalsDirection;
/**
 * Filter to one or more destinations, e.g. "Wimbledon" — pass multiple to accept every station on a branch (including short-turning trains), useful for branched lines like the District line. Repeat the param for multiple values.
 */
destinationName?: string | string[];
/**
 * Maximum number of arrivals to return
 * @minimum 1
 * @maximum 50
 */
limit?: number;
};

export type GetTflArrivalsDirection = typeof GetTflArrivalsDirection[keyof typeof GetTflArrivalsDirection];


export const GetTflArrivalsDirection = {
  inbound: 'inbound',
  outbound: 'outbound',
} as const;

export type GetTflArrivals200ArrivalsItem = {
  lineId: string;
  lineName: string;
  platformName: string;
  direction: string;
  destinationName: string;
  /** Seconds until arrival */
  timeToStationSeconds: number;
  /** ISO timestamp of expected arrival */
  expectedArrival: string;
  /** Human-readable current position of the train, e.g. "At Green Park" */
  currentLocation: string;
};

export type GetTflArrivals200 = {
  arrivals: GetTflArrivals200ArrivalsItem[];
};

export type GetTflArrivals500 = {
  /** Error message */
  error: string;
};

export type GetTflBranchesParams = {
/**
 * TfL StopPoint ID to board at
 * @minLength 1
 */
stopPointId: string;
/**
 * e.g. "district"
 * @minLength 1
 */
lineId: string;
/**
 * Direction of travel from stopPointId
 */
direction: GetTflBranchesDirection;
};

export type GetTflBranchesDirection = typeof GetTflBranchesDirection[keyof typeof GetTflBranchesDirection];


export const GetTflBranchesDirection = {
  inbound: 'inbound',
  outbound: 'outbound',
} as const;

export type GetTflBranches200BranchesItem = {
  /** The branch's actual far terminus, e.g. "Wimbledon" */
  terminus: string;
  /** Every station downstream of stopPointId on this branch, in travel order — i.e. every value a live arrival's destinationName could legitimately take for a train still on this branch, including ones that short-turn before reaching the terminus */
  destinations: string[];
};

export type GetTflBranches200 = {
  branches: GetTflBranches200BranchesItem[];
};

export type GetTflBranches500 = {
  /** Error message */
  error: string;
};

export const getGetAuthLoginUrl = (params?: GetAuthLoginParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/login?${stringifiedParams}` : `/auth/login`
}

export const getAuthLogin = async (params?: GetAuthLoginParams, options?: Parameters<typeof customFetch>[1]): Promise<unknown> => {

  return customFetch<unknown>(getGetAuthLoginUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetAuthCallbackUrl = (params?: GetAuthCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/callback?${stringifiedParams}` : `/auth/callback`
}

export const getAuthCallback = async (params?: GetAuthCallbackParams, options?: Parameters<typeof customFetch>[1]): Promise<unknown> => {

  return customFetch<unknown>(getGetAuthCallbackUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetAuthSessionUrl = () => {




  return `/auth/session`
}

export const getAuthSession = async ( options?: Parameters<typeof customFetch>[1]): Promise<GetAuthSession200> => {

  return customFetch<GetAuthSession200>(getGetAuthSessionUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getPostAuthLogoutUrl = (params?: PostAuthLogoutParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/logout?${stringifiedParams}` : `/auth/logout`
}

export const postAuthLogout = async (params?: PostAuthLogoutParams, options?: Parameters<typeof customFetch>[1]): Promise<PostAuthLogout200> => {

  return customFetch<PostAuthLogout200>(getPostAuthLogoutUrl(params),
  {
    ...options,
    method: 'POST'


  }
);}



export const getGetApiRecommendationsIdUrl = (id: string,) => {




  return `/api/recommendations/${id}`
}

export const getApiRecommendationsId = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<GetApiRecommendationsId200> => {

  return customFetch<GetApiRecommendationsId200>(getGetApiRecommendationsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getPostApiRecommendationsAddEmailUrl = () => {




  return `/api/recommendations/add-email`
}

export const postApiRecommendationsAddEmail = async (postApiRecommendationsAddEmailBody?: PostApiRecommendationsAddEmailBody, options?: Parameters<typeof customFetch>[1]): Promise<PostApiRecommendationsAddEmail200> => {
    const formUrlEncoded = new URLSearchParams();
if(postApiRecommendationsAddEmailBody?.id !== undefined) {
 formUrlEncoded.append(`id`, postApiRecommendationsAddEmailBody.id);
 }
if(postApiRecommendationsAddEmailBody?.email !== undefined) {
 formUrlEncoded.append(`email`, postApiRecommendationsAddEmailBody.email);
 }
if(postApiRecommendationsAddEmailBody?.recurring !== undefined) {
 formUrlEncoded.append(`recurring`, postApiRecommendationsAddEmailBody.recurring);
 }

  return customFetch<PostApiRecommendationsAddEmail200>(getPostApiRecommendationsAddEmailUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body: formUrlEncoded
  }
);}



export const getPostApiRecommendationsDeleteEmailUrl = () => {




  return `/api/recommendations/delete-email`
}

export const postApiRecommendationsDeleteEmail = async (postApiRecommendationsDeleteEmailBody: PostApiRecommendationsDeleteEmailBody, options?: Parameters<typeof customFetch>[1]): Promise<PostApiRecommendationsDeleteEmail200> => {
    const formUrlEncoded = new URLSearchParams();
formUrlEncoded.append(`requestId`, postApiRecommendationsDeleteEmailBody.requestId);

  return customFetch<PostApiRecommendationsDeleteEmail200>(getPostApiRecommendationsDeleteEmailUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body: formUrlEncoded
  }
);}



export const getPostApiRecommendationsFromBookcaseUrl = () => {




  return `/api/recommendations/from-bookcase`
}

export const postApiRecommendationsFromBookcase = async (postApiRecommendationsFromBookcaseBody?: PostApiRecommendationsFromBookcaseBody, options?: Parameters<typeof customFetch>[1]): Promise<PostApiRecommendationsFromBookcase200> => {
    const formData = new FormData();
if(postApiRecommendationsFromBookcaseBody?.bookcase !== undefined) {
 formData.append(`bookcase`, postApiRecommendationsFromBookcaseBody.bookcase);
 }

  return customFetch<PostApiRecommendationsFromBookcase200>(getPostApiRecommendationsFromBookcaseUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}



export const getGetApiQueueDueRecommendationsUrl = () => {




  return `/api/queue-due-recommendations`
}

export const getApiQueueDueRecommendations = async ( options?: Parameters<typeof customFetch>[1]): Promise<void> => {

  return customFetch<void>(getGetApiQueueDueRecommendationsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetApiReextractRecurringBooksUrl = () => {




  return `/api/reextract-recurring-books`
}

export const getApiReextractRecurringBooks = async ( options?: Parameters<typeof customFetch>[1]): Promise<GetApiReextractRecurringBooks200> => {

  return customFetch<GetApiReextractRecurringBooks200>(getGetApiReextractRecurringBooksUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getPostMcpAuthTokenUrl = () => {




  return `/mcp/auth/token`
}

/**
 * Exchange a Cognito JWT for a long-lived MCP JWT token
 */
export const postMcpAuthToken = async ( options?: Parameters<typeof customFetch>[1]): Promise<PostMcpAuthToken200> => {

  return customFetch<PostMcpAuthToken200>(getPostMcpAuthTokenUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export const getGetMiseRecipesUrl = () => {




  return `/mise/recipes`
}

/**
 * Get all recipes for the authenticated user
 */
export const getMiseRecipes = async ( options?: Parameters<typeof customFetch>[1]): Promise<GetMiseRecipes200> => {

  return customFetch<GetMiseRecipes200>(getGetMiseRecipesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetMiseRecipesSearchUrl = (params: GetMiseRecipesSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/mise/recipes/search?${stringifiedParams}` : `/mise/recipes/search`
}

/**
 * Search recipes by name, description, ingredients, or instructions
 */
export const getMiseRecipesSearch = async (params: GetMiseRecipesSearchParams, options?: Parameters<typeof customFetch>[1]): Promise<GetMiseRecipesSearch200> => {

  return customFetch<GetMiseRecipesSearch200>(getGetMiseRecipesSearchUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getDeleteMiseRecipesUuidUrl = (uuid: string,) => {




  return `/mise/recipes/${uuid}`
}

/**
 * Delete a recipe for the authenticated user
 */
export const deleteMiseRecipesUuid = async (uuid: string, options?: Parameters<typeof customFetch>[1]): Promise<DeleteMiseRecipesUuid200> => {

  return customFetch<DeleteMiseRecipesUuid200>(getDeleteMiseRecipesUuidUrl(uuid),
  {
    ...options,
    method: 'DELETE'


  }
);}



export const getGetMiseMealPlanUrl = () => {




  return `/mise/meal-plan`
}

/**
 * Get the meal plan for the authenticated user
 */
export const getMiseMealPlan = async ( options?: Parameters<typeof customFetch>[1]): Promise<MealPlan> => {

  return customFetch<MealPlan>(getGetMiseMealPlanUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getPutMiseMealPlanUrl = () => {




  return `/mise/meal-plan`
}

/**
 * Update the meal plan for the authenticated user
 */
export const putMiseMealPlan = async (mealPlan: MealPlan, options?: Parameters<typeof customFetch>[1]): Promise<PutMiseMealPlan200> => {

  return customFetch<PutMiseMealPlan200>(getPutMiseMealPlanUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(mealPlan)
  }
);}



export const getGetMiseShoppingListUrl = (params?: GetMiseShoppingListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["dates"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }


  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/mise/shopping-list?${stringifiedParams}` : `/mise/shopping-list`
}

/**
 * Get aggregated shopping list from recipes in the meal plan, optionally filtered by date range
 */
export const getMiseShoppingList = async (params?: GetMiseShoppingListParams, options?: Parameters<typeof customFetch>[1]): Promise<GetMiseShoppingList200Item[]> => {

  return customFetch<GetMiseShoppingList200Item[]>(getGetMiseShoppingListUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getPostMiseS3SignedUrlUrl = () => {




  return `/mise/s3/signed-url`
}

/**
 * Generate a signed GET URL for downloading files from S3
 */
export const postMiseS3SignedUrl = async (postMiseS3SignedUrlBody: PostMiseS3SignedUrlBody, options?: Parameters<typeof customFetch>[1]): Promise<PostMiseS3SignedUrl200> => {

  return customFetch<PostMiseS3SignedUrl200>(getPostMiseS3SignedUrlUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postMiseS3SignedUrlBody)
  }
);}



export const getPostMiseS3UploadUrl = () => {




  return `/mise/s3/upload`
}

/**
 * Generate a signed PUT URL for uploading files to S3
 */
export const postMiseS3Upload = async (postMiseS3UploadBody: PostMiseS3UploadBody, options?: Parameters<typeof customFetch>[1]): Promise<PostMiseS3Upload200> => {

  return customFetch<PostMiseS3Upload200>(getPostMiseS3UploadUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postMiseS3UploadBody)
  }
);}



export const getPostMiseS3DeleteUrl = () => {




  return `/mise/s3/delete`
}

/**
 * Delete a file from S3
 */
export const postMiseS3Delete = async (postMiseS3DeleteBody: PostMiseS3DeleteBody, options?: Parameters<typeof customFetch>[1]): Promise<PostMiseS3Delete200> => {

  return customFetch<PostMiseS3Delete200>(getPostMiseS3DeleteUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postMiseS3DeleteBody)
  }
);}



export const getPostMiseParseRecipeUrl = () => {




  return `/mise/parse-recipe`
}

/**
 * Parse natural language recipe text and save to the user account
 */
export const postMiseParseRecipe = async (postMiseParseRecipeBody: PostMiseParseRecipeBody, options?: Parameters<typeof customFetch>[1]): Promise<Recipe> => {

  return customFetch<Recipe>(getPostMiseParseRecipeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postMiseParseRecipeBody)
  }
);}



export const getGetTflStationsUrl = (params: GetTflStationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/tfl/stations?${stringifiedParams}` : `/tfl/stations`
}

/**
 * Search for tube stations by name
 */
export const getTflStations = async (params: GetTflStationsParams, options?: Parameters<typeof customFetch>[1]): Promise<GetTflStations200> => {

  return customFetch<GetTflStations200>(getGetTflStationsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetTflArrivalsUrl = (params: GetTflArrivalsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["destinationName"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/tfl/arrivals?${stringifiedParams}` : `/tfl/arrivals`
}

/**
 * Get the next arrivals for a station, optionally filtered by line and direction
 */
export const getTflArrivals = async (params: GetTflArrivalsParams, options?: Parameters<typeof customFetch>[1]): Promise<GetTflArrivals200> => {

  return customFetch<GetTflArrivals200>(getGetTflArrivalsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetTflBranchesUrl = (params: GetTflBranchesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/tfl/branches?${stringifiedParams}` : `/tfl/branches`
}

/**
 * Get the physical branches available from a station in a given direction, derived from TfL's line topology — lets a favourite be scoped to a whole branch (e.g. every station on the Wimbledon branch) rather than one specific train destination
 */
export const getTflBranches = async (params: GetTflBranchesParams, options?: Parameters<typeof customFetch>[1]): Promise<GetTflBranches200> => {

  return customFetch<GetTflBranches200>(getGetTflBranchesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}
